
### REST extension to manual test the server
GET http://localhost:3001/api/sessions/current HTTP/1.1

### 

POST http://localhost:3001/api/sessions/ HTTP/1.1
content-type: application/json

{
    "email": "mario.rossi@studenti.polito.it",
    "password": "200001"
}

###
DELETE http://localhost:3001/api/sessions/current HTTP/1.1
content-type: application/json


###
#test insertion of a new application
POST http://localhost:3001/api/newapplication HTTP/1.1
content-type: application/json

{
    "studentId": "200001",
    "proposalId": "3"
}
