
### REST extension to manual test the server
GET http://localhost:3001/api/sessions/current HTTP/1.1

### 

POST http://localhost:3001/api/sessions/ HTTP/1.1
content-type: application/json

{
    "email": "mario.rossi@studenti.polito.it",
    "password": "200001"
}

###
DELETE http://localhost:3001/api/sessions/current HTTP/1.1
content-type: application/json

###
#test insertion of a new application
POST http://localhost:3001/api/newapplication HTTP/1.1
content-type: application/json

{
    "studentId": "200001",
    "proposalId": "3"
}
###
#test the API for getting proposals
GET http://localhost:3001/api/proposals/LM-1

#test API for getting cosupervisors list
GET http://localhost:3001/api/cosupervisors HTTP/1.1

###
# test api for getting degrees info
GET http://localhost:3001/api/degrees HTTP/1.1

###
#test api for inserting a new proposal
POST http://localhost:3001/api/newproposal HTTP/1.1
content-type: application/json

{
    "title": "test title2",
    "supervisor": "268556",
    "cosupervisors": ["Maria Rossi, 268553, DAD", "Marco Rossi, REPLY", "Stefano Mariani, 268565, DAT"],
    "keywords": "test1, test2",
    "type": "Abroad Thesis",
    "groups": [],
    "description": "test description",
    "requirements": "test requirements",
    "notes": "test notes",
    "expiration": "22-10-2028",
    "level": "Bachelor",
    "cds": ["LM-1", "LM-2"]
}
