
### REST extension to manual test the server
GET http://localhost:3001/api/sessions/current HTTP/1.1

### 

POST http://localhost:3001/api/sessions/ HTTP/1.1
content-type: application/json

{
    "email": "maria.rossi@polito.it",
    "password": "268553"
}

###
DELETE http://localhost:3001/api/sessions/current HTTP/1.1
content-type: application/json

###
#test insertion of a new application
POST http://localhost:3001/api/newapplication HTTP/1.1
content-type: application/json

{
    "studentId": "200003",
    "proposalId": "4"
}

###
#test the API for getting proposals
GET http://localhost:3001/api/thesis/

#test API for getting cosupervisors list
GET http://localhost:3001/api/cosupervisors HTTP/1.1

###
# test api for getting degrees info
GET http://localhost:3001/api/degrees HTTP/1.1

###
#test api for inserting a new proposal
POST http://localhost:3001/api/newproposal HTTP/1.1
content-type: application/json

{
    "title": "test title2",
    "supervisor": "268556",
    "cosupervisors": [],
    "keywords": "test1, test2",
    "type": "Abroad Thesis",
    "groups": [],
    "description": "test description",
    "requirements": "test requirements",
    "notes": "test notes",
    "expiration": "31/12/2023",
    "level": "Bachelor",
    "cds": ["LM-1", "LM-2"]
}

###
#test api for handling virtual clock changes
PUT http://localhost:3001/api/clockchanged HTTP/1.1
content-type: application/json

{
    "selectedTimestamp": "01/01/2024"
}

###
# change virtual clock back
PUT http://localhost:3001/api/clockchanged HTTP/1.1
content-type: application/json

{
    "selectedTimestamp": "11/12/2023"
}

### 
POST http://localhost:3001/api/sessions/ HTTP/1.1
content-type: application/json

{
    "email": "maria.rossi@polito.it",
    "password": "268553"
}
###
#test the API for getting applications for a proposal

GET http://localhost:3001/api/teacher/applications/

###
# test api for retrieving student applications
GET http://localhost:3001/api/student/applications/200001 HTTP/1.1 
#seems ok

GET http://localhost:3001/api/applications/

###
PUT http://localhost:3001/api/applications/1 
content-type: application/json

{
    "decision":"rejected",
    "studentId":200001
}

###
# test student gets thesis proposals
GET http://localhost:3001/api/thesis/student/LM-1


###
# test teacher gets own proposals
GET http://localhost:3001/api/thesis/teacher/268555


###
#test teacher can archive own proposal
#NOTE: userId is given just for test purposes, in real app this will be taken from req.user
PUT http://localhost:3001/api/teacher/archiveproposal
content-type: application/json

{
    "proposalId": "3",
    "userId": "268553" 
}

###
#test update proposal
PUT http://localhost:3001/api/teacher/proposal/2
content-type: application/json

{   
    "id":2,
    "title": "test title2",
    "supervisor": "268556,Nome Cognome",
    "cosupervisors": ["Luigi Bianchi, 268554, DAUIN"],
    "keywords": "test1, test2",
    "type": "Abroad Thesis",
    "groups": [],
    "description": "test description",
    "requirements": "test requirements",
    "notes": "test notes",
    "expiration": "31/12/2023",
    "level": "master",
    "cds": ["LM-1", "LM-2"]
}

###
# test delete proposal
DELETE http://localhost:3001/api/deleteproposal/3